version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-195-169-25.compute-1.amazonaws.com
            database: dbt4c8vjab5k3m
            user: mzvfrdpagjmsbp
            password: 51634c13996923078a141d9db27f9bcdc1bcc7bd27b3a1fd4649ab8f3abdbcf5
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true